-- =========================================================
-- SASI STEEL ENGINEERING - COMPLETE SUPABASE DATABASE SCHEMA
-- Run this script in Supabase Dashboard -> SQL Editor -> Run
-- =========================================================

-- 1. ATTENDANCE TABLE
CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  employee_name TEXT NOT NULL,
  role TEXT NOT NULL, -- 'Manager', 'Computer', 'Powder coating mestri', 'Powder coating helper', 'Welding mestri', 'Welding helper', 'Polished mestri', 'Polished helpers', 'Helpers', 'Pvd mestri', 'Pvd helpers', etc.
  attendance_date DATE DEFAULT CURRENT_DATE NOT NULL,
  status TEXT NOT NULL, -- 'Present', 'Absent', 'Half Day', 'Overtime'
  hours_worked NUMERIC DEFAULT 8.0,
  overtime_hours NUMERIC DEFAULT 0.0,
  wage_rate NUMERIC DEFAULT 0.0,
  notes TEXT
);

-- 2. INVENTORY TABLE
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  item_name TEXT NOT NULL,
  category TEXT NOT NULL, -- 'Raw Steel', 'Structural Beams', 'Plates & Sheets', 'Welding Consumables', 'Hardware & Fasteners'
  sku TEXT,
  quantity NUMERIC NOT NULL DEFAULT 0,
  unit TEXT NOT NULL DEFAULT 'Units', -- 'Tons', 'Meters', 'Sheets', 'Kgs', 'Boxes'
  min_reorder_level NUMERIC DEFAULT 5,
  unit_price NUMERIC DEFAULT 0.0,
  storage_location TEXT, -- 'Yard A', 'Rack 04', 'Shed 2'
  status TEXT DEFAULT 'In Stock', -- 'In Stock', 'Low Stock', 'Out of Stock'
  notes TEXT
);

-- 3. INQUIRIES & QUOTATIONS TABLE
CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  client_name TEXT NOT NULL,
  client_phone TEXT NOT NULL,
  client_email TEXT,
  project_type TEXT NOT NULL,
  project_scope TEXT,
  estimated_cost TEXT,
  blueprint_url TEXT, -- Cloudinary URL
  message TEXT,
  status TEXT DEFAULT 'New', -- 'New', 'Contacted', 'Quoted', 'Completed', 'Cancelled'
  assigned_to TEXT
);

-- 4. EXPENSES & INCOME (FINANCE) TABLE
CREATE TABLE IF NOT EXISTS finance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  entry_type TEXT NOT NULL, -- 'Income' or 'Expense'
  category TEXT NOT NULL, -- 'Client Payment', 'Raw Material Purchase', 'Labor Wages', 'Equipment & Maintenance', 'Transport & Crane', 'Utilities'
  amount NUMERIC NOT NULL,
  transaction_date DATE DEFAULT CURRENT_DATE NOT NULL,
  payment_mode TEXT DEFAULT 'Bank Transfer', -- 'Cash', 'UPI', 'Bank Transfer', 'Cheque'
  receipt_url TEXT, -- Cloudinary receipt image
  description TEXT,
  reference_no TEXT
);

-- 5. PRODUCTS CATALOG TABLE
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  category_slug TEXT NOT NULL,
  price_formatted TEXT NOT NULL,
  badge TEXT,
  image_url TEXT NOT NULL, -- Cloudinary or static URL
  specs TEXT,
  description TEXT,
  is_featured BOOLEAN DEFAULT false
);

-- 6. GALLERY TABLE
CREATE TABLE IF NOT EXISTS gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL, -- 'Steel Fabrication', 'Welding Works', 'Storage & Racks', 'Mezzanine Floors', 'Custom Interiors'
  image_url TEXT NOT NULL, -- Cloudinary URL
  caption TEXT,
  location TEXT,
  is_featured BOOLEAN DEFAULT true
);

-- 7. ADMIN USERS TABLE (For Custom Password Verification)
CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL, -- Simple secure token or pin
  role TEXT DEFAULT 'Admin'
);

-- Insert Default Admin (Username: admin, Password: 123456789)
INSERT INTO admin_users (username, password_hash, role)
VALUES ('admin', '123456789', 'Super Admin')
ON CONFLICT (username) DO NOTHING;

-- 8. EMPLOYEES / WORKSHOP WORKERS TABLE
CREATE TABLE IF NOT EXISTS employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  phone TEXT,
  role TEXT NOT NULL, -- 'Manager', 'Computer', 'Powder coating mestri', 'Powder coating helper', 'Welding mestri', 'Welding helper', 'Polished mestri', 'Polished helpers', 'Helpers', 'Pvd mestri', 'Pvd helpers', etc.
  daily_wage NUMERIC DEFAULT 800.0,
  join_date DATE DEFAULT CURRENT_DATE,
  status TEXT DEFAULT 'Active', -- 'Active', 'Inactive', 'On Leave'
  emergency_contact TEXT,
  notes TEXT
);

-- 9. ORDERS MANAGEMENT TABLE
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  order_number TEXT,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  delivery_address TEXT,
  inventory_item_id BIGINT,
  item_name TEXT NOT NULL,
  category TEXT,
  quantity NUMERIC NOT NULL DEFAULT 1,
  unit TEXT DEFAULT 'Units',
  unit_price NUMERIC NOT NULL DEFAULT 0,
  total_amount NUMERIC NOT NULL DEFAULT 0,
  payment_status TEXT DEFAULT 'Pending', -- 'Paid', 'Partial', 'Pending'
  order_status TEXT DEFAULT 'Confirmed', -- 'Pending', 'Confirmed', 'Processing', 'Delivered', 'Cancelled'
  order_date DATE DEFAULT CURRENT_DATE NOT NULL,
  expected_delivery DATE,
  notes TEXT
);

-- 10. GENERATED OFFICIAL QUOTATIONS TABLE
CREATE TABLE IF NOT EXISTS quotations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  quote_number TEXT UNIQUE NOT NULL,
  quote_date DATE DEFAULT CURRENT_DATE NOT NULL,
  validity_days INTEGER DEFAULT 15,
  customer_name TEXT NOT NULL,
  company_name TEXT,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  customer_address TEXT,
  customer_gst TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  sub_total NUMERIC DEFAULT 0.0,
  packing_charges NUMERIC DEFAULT 0.0,
  gst_rate NUMERIC DEFAULT 18.0,
  gst_amount NUMERIC DEFAULT 0.0,
  other_charges NUMERIC DEFAULT 0.0,
  other_charges_desc TEXT,
  grand_total NUMERIC DEFAULT 0.0,
  amount_in_words TEXT,
  bank_details JSONB,
  terms JSONB,
  status TEXT DEFAULT 'Draft', -- 'Draft', 'Sent', 'Approved', 'Rejected', 'Completed'
  notes TEXT,
  created_by TEXT DEFAULT 'Admin'
);

-- 11. COMPANY QUOTATION CONFIGURATION TABLE
CREATE TABLE IF NOT EXISTS quotation_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  company_name TEXT DEFAULT 'SASI STEEL ENGINEERING & WELDING WORKS',
  company_tagline TEXT DEFAULT 'Heavy Structural Fabrication & Certified Welding Specialists',
  company_logo TEXT,
  company_address TEXT DEFAULT '128-56/4, guntur amaravathi road, gorantla,guntur,a.p',
  company_phone TEXT DEFAULT 'PH: 9949321664, OFFICE: 8333991114(OR)5',
  company_email TEXT DEFAULT 'sasisteels863@gmail.com',
  company_gstin TEXT DEFAULT '37AUCPA2925Q1ZG,CODE :37.',
  bank_name TEXT DEFAULT 'STATE BANK OF INDIA, Arundalpet',
  account_holder TEXT DEFAULT 'SASI STEEL ENGINEERING & WELDING WORKS',
  account_number TEXT DEFAULT '42384233004',
  ifsc_code TEXT DEFAULT 'SBIN0001234',
  branch_name TEXT DEFAULT 'Arundalpet, Guntur',
  upi_id TEXT DEFAULT '9949321664@upi',
  security_pin_hash TEXT,
  default_terms JSONB DEFAULT '["Items will be ready within 30-45 working days form the date of Approval.", "Price ex-works, 60% Advance along with Work Order, 30% against delivery, balance 10% payment after installation", "Above rates are excluding of GST, will be applicable @ 18%", "Installation/Mechanic/oil of above fixtures on site is not in our scope of work, If it is then it will be charge extra 6-8% on base value for above one lakh, Rs2000 per head below one lakh.", "Above rates are excluding of loading, unloading & transportation Charges, It will be charge extra at actuals, Packing charges 4% extra.", "Above rates are approximately and are likely to be change, according to the (Market/Rawmaterials) conditions.", "This Quotation is valid for 15days from the date of issue."]'::jsonb
);

-- =========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =========================================================

ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_settings ENABLE ROW LEVEL SECURITY;

-- Allow Public Access (SELECT & INSERT for public frontend, full CRUD for Admin)
CREATE POLICY "Public read inquiries" ON inquiries FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public read products" ON products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public read gallery" ON gallery FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public read attendance" ON attendance FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public read inventory" ON inventory FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public read finance" ON finance FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public read admin_users" ON admin_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public read employees" ON employees FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public read orders" ON orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public read quotations" ON quotations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public read quotation_settings" ON quotation_settings FOR ALL USING (true) WITH CHECK (true);

-- Insert Initial Sample Employees
INSERT INTO employees (name, phone, role, daily_wage, status, notes)
VALUES
('Ramesh Kumar', '+91 98480 12345', 'Welding mestri', 950.0, 'Active', 'Senior Welding Specialist'),
('Suresh Rao', '+91 98480 23456', 'Powder coating mestri', 900.0, 'Active', 'Powder Coating Lead'),
('Venkatesh M', '+91 98480 34567', 'Manager', 1300.0, 'Active', 'Workshop Operations Manager'),
('Rajesh V', '+91 98480 45678', 'Helpers', 600.0, 'Active', 'Workshop Assistant')
ON CONFLICT DO NOTHING;

-- Insert Initial Sample Orders
INSERT INTO orders (order_number, customer_name, customer_phone, item_name, category, quantity, unit, unit_price, total_amount, payment_status, order_status, order_date, notes)
VALUES
('ORD-1001', 'Kavitha Infra Projects', '+91 98480 88990', 'Galvalume Corrugated Roofing Sheets', 'Plates & Sheets', 50, 'Sheets', 380, 19000, 'Paid', 'Processing', CURRENT_DATE, 'Urgent delivery for factory roof repair'),
('ORD-1002', 'Sri Balaji Engineering', '+91 98480 77665', 'Heavy-Duty Warehouse Pallet Racks', 'Structural Steel', 4, 'Tons', 4200, 16800, 'Partial', 'Confirmed', CURRENT_DATE, 'Guntur bypass site delivery')
ON CONFLICT DO NOTHING;

-- Insert Default Initial Products
INSERT INTO products (name, category, category_slug, price_formatted, badge, image_url, specs, description, is_featured)
VALUES 
('Architectural Gold Metal Interior Room Divider & Partition Screen', 'Custom Fabrication', 'custom-fabrication', '₹14,500 / unit', 'Luxury Gold PVD', 'product-gold-partition-divider.png', 'Gold PVD Coated Steel | Vertical Slat Divider | 5 Integrated Planter Shelves', 'Modern luxury architectural metal room divider and partition screen fabricated with gold PVD coated steel slats and integrated wooden planter boxes. Perfect for living rooms, offices, and boutique showroom spaces.', true),
('Showroom Saree & Apparel Display Island Racks', 'Storage Systems', 'storage-systems', '₹12,500 / unit', 'SS & Glass Shelving', 'product-island-display-rack.png', 'Polished Stainless Steel Frame | Multi-Tier Glass Shelves | Blouse & Saree Rails', 'Premium retail showroom island display racks designed with high-grade stainless steel frames, multi-tier tempered glass shelving for saree stacks, and extended side hanging arms for apparel presentation.', true),
('Commercial Showroom & Apparel Steel Display Racks', 'Storage Systems', 'storage-systems', '₹6,500 / unit bay', 'Showroom Grade', 'product-display-racks.png', 'Matte Black Powder Coat | Modular Hanging Rails | Wooden Shelf Mounts', 'Architectural showroom steel display racks, heavy garment hanging fixtures, and boutique retail shelving fabricated with precision welded steel tubing.', true),
('Stainless Steel Showroom Mirror Trolleys & Retail Fixtures', 'Custom Fabrication', 'custom-fabrication', '₹8,800 / unit', 'SS 304 Polished', 'product-ss-display-mirror.png', '304 Stainless Steel Frame | Heavy-Duty 360° Castors | Full-Length Mirror Mount', 'Premium stainless steel movable full-length trial mirror units, showroom apparel fixtures, and retail display trolleys with locking caster wheels and mirror polish.', true),
('Heavy-Duty Warehouse Pallet Racks', 'Storage Systems', 'storage-systems', '₹4,200 / bay level', '3.5 Ton Capacity', 'product-racks.jpg', 'Upright Height: 2m to 10m | Beam Length: 2.7m | Powder Coated', 'Multi-tier selective pallet racking systems engineered for forklift loading, high-density warehousing, and extreme seismic resistance.', true),
('Galvalume Corrugated Roofing Sheets', 'PEB & Roofing', 'peb-roofing', '₹380 / sq.meter', 'AZ-150 Coating', 'product-sheets.jpg', 'Thickness: 0.45 - 0.60 mm | Color Coated | Wind Tested', 'Weather-resistant, corrosion-proof profiled steel roofing and wall cladding sheets for industrial factory sheds and commercial buildings.', false)
ON CONFLICT DO NOTHING;
